### ISSUE TITLE
use greenback to yield across generators

### ISSUE THREAD

**Issue by hu6360567** [oremanj/greenback#21]
Hi, 

The problem is describe [here](https://stackoverflow.com/questions/76625801/yielding-from-generator-to-another-generator-in-a-same-thread).

Somehow, I found greenback makes the sync code can interact with async code in async context. My 2nd attempts somehow works out, but the queue is not limited to 1, which set as max_size.
Also, is there any recommendation for my example code. It really messed up to get result from in-thread event loop.

**Comment by oremanj** [comment]
greenback is not the right tool for this; there's no async environment involved in your program. It looks like you got a useful response to your question on stackoverflow, so I'm going to close this issue.
