### ISSUE TITLE
Request for Conda package

### ISSUE THREAD

**Issue by serinamarie** [oremanj/greenback#29]
In our [latest release](https://github.com/PrefectHQ/prefect/releases/tag/2.15.0) at Prefect, we added `greenback` as a dependency and noticed that it is not available on conda-forge or other channels, which definitely presents a challenge for us. 

Would it be possible to consider creating a Conda package for `greenback` and hosting it on conda-forge?

We would also be happy to assist or contribute to this process, in terms of writing the recipe.

Thanks for your time!

**Comment by oremanj** [comment]
I am not familiar with Conda. This is a pure-Python package which is packaged using the standard Python packaging tools. What's preventing Conda from using it in its current form?

**Comment by peterbygrave** [comment]
I have begun process of adding to conda-forge: https://github.com/conda-forge/staged-recipes/pull/25485

@oremanj Do you want to be added as a maintainer of the recipe?

Note: this is not the same as package author/maintainer which is obviously you and is completely up to you - https://conda-forge.org/docs/maintainer/adding_pkgs/#maintainer-role
Note: conda-forge requires explicit approval from the individual before being added as a maintainer

**Comment by oremanj** [comment]
Thank you! I would prefer not to take on maintainership responsibilities for an ecosystem that I'm not familiar with. I'm happy to review PRs to greenback that make it more conda-friendly if there are any changes needed.

**Comment by peterbygrave** [comment]
Sounds good. Looks like library is conda friendly and the conda-forge ecosystem will monitor any releases to pypi and auto update itself. I can resolve any problems in that end and will come back to this repo when appropriate 👍

Not sure what is holding up the linked PR, but will come back when all resolved and released. 

Thanks again

**Comment by serinamarie** [comment]
Thanks so much for taking this up, @peterbygrave!

I'm unable to link this issue to your PR, but merging that PR would close this issue :)

**Comment by peterbygrave** [comment]
This package is now available on conda-forge https://anaconda.org/conda-forge/greenback

And it [auto updated](https://github.com/conda-forge/greenback-feedstock/pull/1) the release from @oremanj releasing to pypi, and I was able to merge to make release of 1.2.1.

With this we can close this issue

Thanks everyone.
